In [1]:
# set tf 1.x for colab
%tensorflow_version 1.x

UsageError: Line magic function `%tensorflow_version` not found.


# Video "What is TensorFlow"

In [2]:
%config IPCompleter.greedy=True

In [3]:
import tensorflow as tf
import numpy as np
print(tf.__version__)

1.15.0


In [4]:
tf.reset_default_graph()
a = tf.placeholder(np.float32, (2, 2))
b = tf.Variable(tf.ones((2, 2)))
c = a @ b

In [5]:
print(c)

Tensor("matmul:0", shape=(2, 2), dtype=float32)


In [6]:
s = tf.InteractiveSession(config=tf.ConfigProto(log_device_placement=True))

Device mapping:
/job:localhost/replica:0/task:0/device:GPU:0 -> device: 0, name: GeForce GTX 1660, pci bus id: 0000:06:00.0, compute capability: 7.5



In [7]:
print(tf.global_variables_initializer())
print(s.run(tf.global_variables_initializer()))
s.run(c, feed_dict={a: np.ones((2, 2))})

name: "init"
op: "NoOp"
input: "^Variable/Assign"

None


InternalError: 2 root error(s) found.
  (0) Internal: Blas GEMM launch failed : a.shape=(2, 2), b.shape=(2, 2), m=2, n=2, k=2
	 [[node matmul (defined at d:\projects\ml\advanced_ml\venv\lib\site-packages\tensorflow_core\python\framework\ops.py:1748) ]]
	 [[matmul/_3]]
  (1) Internal: Blas GEMM launch failed : a.shape=(2, 2), b.shape=(2, 2), m=2, n=2, k=2
	 [[node matmul (defined at d:\projects\ml\advanced_ml\venv\lib\site-packages\tensorflow_core\python\framework\ops.py:1748) ]]
0 successful operations.
0 derived errors ignored.

Original stack trace for 'matmul':
  File "d:\program\anaconda\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\program\anaconda\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "d:\projects\ml\advanced_ml\venv\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "d:\projects\ml\advanced_ml\venv\lib\site-packages\traitlets\config\application.py", line 664, in launch_instance
    app.start()
  File "d:\projects\ml\advanced_ml\venv\lib\site-packages\ipykernel\kernelapp.py", line 583, in start
    self.io_loop.start()
  File "d:\projects\ml\advanced_ml\venv\lib\site-packages\tornado\platform\asyncio.py", line 148, in start
    self.asyncio_loop.run_forever()
  File "d:\program\anaconda\lib\asyncio\base_events.py", line 538, in run_forever
    self._run_once()
  File "d:\program\anaconda\lib\asyncio\base_events.py", line 1782, in _run_once
    handle._run()
  File "d:\program\anaconda\lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "d:\projects\ml\advanced_ml\venv\lib\site-packages\tornado\ioloop.py", line 690, in <lambda>
    lambda f: self._run_callback(functools.partial(callback, future))
  File "d:\projects\ml\advanced_ml\venv\lib\site-packages\tornado\ioloop.py", line 743, in _run_callback
    ret = callback()
  File "d:\projects\ml\advanced_ml\venv\lib\site-packages\tornado\gen.py", line 787, in inner
    self.run()
  File "d:\projects\ml\advanced_ml\venv\lib\site-packages\tornado\gen.py", line 748, in run
    yielded = self.gen.send(value)
  File "d:\projects\ml\advanced_ml\venv\lib\site-packages\ipykernel\kernelbase.py", line 377, in dispatch_queue
    yield self.process_one()
  File "d:\projects\ml\advanced_ml\venv\lib\site-packages\tornado\gen.py", line 225, in wrapper
    runner = Runner(result, future, yielded)
  File "d:\projects\ml\advanced_ml\venv\lib\site-packages\tornado\gen.py", line 714, in __init__
    self.run()
  File "d:\projects\ml\advanced_ml\venv\lib\site-packages\tornado\gen.py", line 748, in run
    yielded = self.gen.send(value)
  File "d:\projects\ml\advanced_ml\venv\lib\site-packages\ipykernel\kernelbase.py", line 361, in process_one
    yield gen.maybe_future(dispatch(*args))
  File "d:\projects\ml\advanced_ml\venv\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "d:\projects\ml\advanced_ml\venv\lib\site-packages\ipykernel\kernelbase.py", line 268, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "d:\projects\ml\advanced_ml\venv\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "d:\projects\ml\advanced_ml\venv\lib\site-packages\ipykernel\kernelbase.py", line 541, in execute_request
    user_expressions, allow_stdin,
  File "d:\projects\ml\advanced_ml\venv\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "d:\projects\ml\advanced_ml\venv\lib\site-packages\ipykernel\ipkernel.py", line 300, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "d:\projects\ml\advanced_ml\venv\lib\site-packages\ipykernel\zmqshell.py", line 536, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "d:\projects\ml\advanced_ml\venv\lib\site-packages\IPython\core\interactiveshell.py", line 2858, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "d:\projects\ml\advanced_ml\venv\lib\site-packages\IPython\core\interactiveshell.py", line 2886, in _run_cell
    return runner(coro)
  File "d:\projects\ml\advanced_ml\venv\lib\site-packages\IPython\core\async_helpers.py", line 68, in _pseudo_sync_runner
    coro.send(None)
  File "d:\projects\ml\advanced_ml\venv\lib\site-packages\IPython\core\interactiveshell.py", line 3063, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File "d:\projects\ml\advanced_ml\venv\lib\site-packages\IPython\core\interactiveshell.py", line 3254, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "d:\projects\ml\advanced_ml\venv\lib\site-packages\IPython\core\interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-4cfbcc6fc584>", line 4, in <module>
    c = a @ b
  File "d:\projects\ml\advanced_ml\venv\lib\site-packages\tensorflow_core\python\ops\math_ops.py", line 912, in binary_op_wrapper
    return func(x, y, name=name)
  File "d:\projects\ml\advanced_ml\venv\lib\site-packages\tensorflow_core\python\util\dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "d:\projects\ml\advanced_ml\venv\lib\site-packages\tensorflow_core\python\ops\math_ops.py", line 2754, in matmul
    a, b, transpose_a=transpose_a, transpose_b=transpose_b, name=name)
  File "d:\projects\ml\advanced_ml\venv\lib\site-packages\tensorflow_core\python\ops\gen_math_ops.py", line 6613, in mat_mul
    name=name)
  File "d:\projects\ml\advanced_ml\venv\lib\site-packages\tensorflow_core\python\framework\op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "d:\projects\ml\advanced_ml\venv\lib\site-packages\tensorflow_core\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "d:\projects\ml\advanced_ml\venv\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "d:\projects\ml\advanced_ml\venv\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "d:\projects\ml\advanced_ml\venv\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()


In [8]:
s.close()

## My test

In [9]:
tf.reset_default_graph()
x = tf.placeholder(tf.float32, shape=(None, 2))
a = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[2, 3], name='a')

y = x @ a
tf.get_default_graph().get_operations()[0]

<tf.Operation 'Placeholder' type=Placeholder>

# Video "Our first model in TensorFlow"

### Simple optimization (with simple prints)

In [10]:
tf.reset_default_graph()
x = tf.get_variable("x", shape=(), dtype=tf.float32, trainable=True)
f = x ** 2

In [11]:
optimizer = tf.train.GradientDescentOptimizer(0.1)
step = optimizer.minimize(f, var_list=[x])

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


In [12]:
tf.trainable_variables()

[<tf.Variable 'x:0' shape=() dtype=float32_ref>]

In [ ]:
with tf.Session(config=tf.ConfigProto(log_device_placement=True)) as s:  # in this way session will be closed automatically
    s.run(tf.global_variables_initializer())
    print()
    for i in range(10):
        _, curr_x, curr_f = s.run([step, x, f])
        print(curr_x, curr_f)

Device mapping:
/job:localhost/replica:0/task:0/device:GPU:0 -> device: 0, name: GeForce GTX 1660, pci bus id: 0000:06:00.0, compute capability: 7.5



### Simple optimization (with tf.Print)

In [14]:
tf.reset_default_graph()
x = tf.get_variable("x", shape=(), dtype=tf.float32)
f = x ** 2
f = tf.Print(f, [x, f], "x, f:")

Instructions for updating:
Use tf.print instead of tf.Print. Note that tf.print returns a no-output operator that directly prints the output. Outside of defuns or eager mode, this operator will not be executed unless it is directly specified in session.run or used as a control dependency for other operators. This is only a concern in graph mode. Below is an example of how to ensure tf.print executes in graph mode:



In [15]:
optimizer = tf.train.GradientDescentOptimizer(0.1)
step = optimizer.minimize(f)

In [16]:
with tf.Session() as s:
    s.run(tf.global_variables_initializer())
    for i in range(10):
        s.run([step, f])

In [44]:
# Prints to jupyter server stdout (not available in Coursera Notebooks):
# 2018-07-21 18:01:27.308270: I tensorflow/core/kernels/logging_ops.cc:79] x, f:[-1.0670249][1.1385423]
# 2018-07-21 18:01:27.308809: I tensorflow/core/kernels/logging_ops.cc:79] x, f:[-0.85361993][0.72866696]
# 2018-07-21 18:01:27.309116: I tensorflow/core/kernels/logging_ops.cc:79] x, f:[-0.68289596][0.46634689]
# 2018-07-21 18:01:27.309388: I tensorflow/core/kernels/logging_ops.cc:79] x, f:[-0.54631674][0.29846197]
# 2018-07-21 18:01:27.309678: I tensorflow/core/kernels/logging_ops.cc:79] x, f:[-0.43705338][0.19101566]
# 2018-07-21 18:01:27.309889: I tensorflow/core/kernels/logging_ops.cc:79] x, f:[-0.34964269][0.12225001]
# 2018-07-21 18:01:27.310213: I tensorflow/core/kernels/logging_ops.cc:79] x, f:[-0.27971417][0.078240015]
# 2018-07-21 18:01:27.310475: I tensorflow/core/kernels/logging_ops.cc:79] x, f:[-0.22377133][0.050073609]
# 2018-07-21 18:01:27.310751: I tensorflow/core/kernels/logging_ops.cc:79] x, f:[-0.17901707][0.032047112]
# 2018-07-21 18:01:27.310963: I tensorflow/core/kernels/logging_ops.cc:79] x, f:[-0.14321366][0.020510152]

### Simple optimization (with TensorBoard logging)

In [55]:
tf.reset_default_graph()
x = tf.get_variable("x", shape=(), dtype=tf.float32)
f = x ** 4

In [56]:
optimizer = tf.train.GradientDescentOptimizer(0.1)
step = optimizer.minimize(f)

In [57]:
tf.summary.scalar('curr_x_3', x)
tf.summary.scalar('curr_f_3', f)
summaries = tf.summary.merge_all()

In [58]:
s = tf.InteractiveSession()
summary_writer = tf.summary.FileWriter("logs/1", s.graph)
s.run(tf.global_variables_initializer())
for i in range(20):
    _, curr_summaries = s.run([step, summaries])
    summary_writer.add_summary(curr_summaries, i)
    summary_writer.flush()

Run  `tensorboard --logdir=./logs` in bash

This is what you can see in your browser **(not available in Coursera Notebooks)**
<img src="images/TensorBoard.jpg" style="width:70%">

**If you're running on Google Colab you can still run TensorBoard!**

In [ ]:
# !!! RUN THIS CELL ONLY ON GOOGLE COLAB !!!
! wget https://raw.githubusercontent.com/hse-aml/intro-to-dl/master/setup_google_colab.py -O setup_google_colab.py
import setup_google_colab

# run tensorboard in background
import os
os.system("tensorboard --logdir=./logs --host 0.0.0.0 --port 6006 &")

# expose port and show the link
setup_google_colab.expose_port_on_colab(6006)

In [11]:
s.close()

### Training a linear model

In [146]:
# generate model data
N = 1000
D = 3
x = np.random.random((N, D))
w = np.random.random((D, 1))
y = x @ w + np.random.randn(N, 1) * 0.20

print(x.shape, y.shape)
print(w.T)

(1000, 3) (1000, 1)
[[0.887686   0.59422185 0.30518892]]


In [147]:
tf.reset_default_graph()

features = tf.placeholder(tf.float32, shape=(None, D))
target = tf.placeholder(tf.float32, shape=(None, 1))

weights = tf.get_variable("weights", shape=(D, 1), dtype=tf.float32)

predictions = features @ weights

loss = tf.reduce_mean(tf.abs((target - predictions)) ** 2)

print(target.shape, predictions.shape, loss.shape, b.shape)

(?, 1) (?, 1) () (2,)


In [148]:
optimizer = tf.train.GradientDescentOptimizer(0.1)
step = optimizer.minimize(loss)

In [149]:
print(features)
print(target)
print(weights)
print(predictions)
print(loss)
print(optimizer)
print(step)

Tensor("Placeholder:0", shape=(?, 3), dtype=float32)
Tensor("Placeholder_1:0", shape=(?, 1), dtype=float32)
<tf.Variable 'weights:0' shape=(3, 1) dtype=float32_ref>
Tensor("matmul:0", shape=(?, 1), dtype=float32)
Tensor("Mean:0", shape=(), dtype=float32)
name: "GradientDescent"
op: "NoOp"
input: "^GradientDescent/update_weights/ApplyGradientDescent"



In [151]:
with tf.Session(config=tf.ConfigProto(log_device_placement=True)) as s:
    print(s.run(tf.global_variables_initializer()))
    for i in range(300):
        _, curr_loss, curr_weights = s.run([step, loss, weights], 
                                           feed_dict={features: x, target: y})
        if i % 50 == 0:
            print(curr_loss)

Device mapping:
/job:localhost/replica:0/task:0/device:GPU:0 -> device: 0, name: GeForce GTX 1660, pci bus id: 0000:06:00.0, compute capability: 7.5

None
0.71259576
0.054876246
0.04309354
0.04097931
0.04059982
0.04053168


In [152]:
# found weights
curr_weights.T

array([[0.88897365, 0.5877981 , 0.3078559 ]], dtype=float32)

In [153]:
# true weights
w.T

array([[0.887686  , 0.59422185, 0.30518892]])